packages:
  - packages/*
catalog:
  '@elora-cloud/elora-cli': ^1.0.14
  '@elora-cloud/eslint-config': ^4.5.1
  '@element-plus/icons-vue': ^2.3.1
  '@mistjs/tsconfig-vue': ^1.1.2
  '@pnpm/types': ^1000.4.0
  '@rollup/plugin-typescript': ^12.1.2
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^2.0.10
  '@types/markdown-it-emoji': ^3.0.1
  '@types/node': ^22.14.1
  '@types/uniqid': ^5.3.4
  '@vitejs/plugin-vue': ^5.2.3
  '@vueuse/core': ^13.0.0
  changelogen: ^0.6.1
  element-plus: ^2.9.8
  eslint: ^9.25.0
  highlight.js: ^11.11.1
  husky: ^9.1.7
  lint-staged: ^15.5.1
  markdown-it: ^14.1.0
  markdown-it-anchor: ^9.2.0
  markdown-it-class: ^1.0.0
  markdown-it-container: ^4.0.0
  markdown-it-emoji: ^3.0.0
  markdown-it-toc-done-right: ^4.2.0
  rimraf: ^6.0.1
  rollup: ^4.40.0
  rollup-plugin-typescript2: ^0.36.0
  sass: ^1.86.3
  stylelint: ^16.18.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-scss: ^14.0.0
  typescript: ^5.8.3
  uniqid: ^5.4.0
  unplugin-auto-import: ^19.1.2
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.2
  vite-plugin-dts: ^4.5.3
  vite-plugin-inspect: ^11.0.1
  vitest: ^3.1.1
  vue-tsc: ^2.2.8
  vue: ^3.5.13
  vue-router: ^4.5.0
