packages:
  - packages/*
catalog:
  '@element-plus/icons-vue': ^2.3.1
  '@elora-cloud/elora-cli': ^1.0.14
  '@elora-cloud/eslint-config': ^4.16.2
  '@mistjs/tsconfig-vue': ^1.1.2
  '@pnpm/types': ^1000.6.0
  '@rollup/plugin-typescript': ^12.1.4
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^2.0.10
  '@types/markdown-it-emoji': ^3.0.1
  '@types/node': ^24.0.10
  '@types/uniqid': ^5.3.4
  '@vitejs/plugin-vue': ^6.0.0
  '@vueuse/core': ^13.5.0
  changelogen: ^0.6.1
  element-plus: ^2.10.2
  eslint: ^9.30.1
  highlight.js: ^11.11.1
  husky: ^9.1.7
  lint-staged: ^16.1.2
  markdown-it: ^14.1.0
  markdown-it-anchor: ^9.2.0
  markdown-it-class: ^1.0.0
  markdown-it-container: ^4.0.0
  markdown-it-emoji: ^3.0.0
  markdown-it-toc-done-right: ^4.2.0
  rimraf: ^6.0.1
  rollup: ^4.44.1
  rollup-plugin-typescript2: ^0.36.0
  sass: ^1.89.2
  stylelint: ^16.21.1
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-scss: ^15.0.1
  typescript: ^5.8.3
  uniqid: ^5.4.0
  unplugin-auto-import: ^19.3.0
  unplugin-dts: 1.0.0-beta.2
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.8.0
  vite: ^7.0.2
  vite-plugin-inspect: ^11.3.0
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-router: ^4.5.1
  vue-tsc: ^3.0.1
