packages:
  - packages/*
catalog:
  '@element-plus/icons-vue': ^2.3.2
  '@elora-cloud/elora-cli': ^1.0.16
  '@elora-cloud/eslint-config': ^8.1.1
  '@elora-cloud/unplugin-dts': 1.0.0-beta.10
  '@microsoft/api-extractor': ^7.58.7
  '@pnpm/types': ^1101.0.0
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^4.0.0
  '@types/markdown-it-emoji': ^3.0.1
  '@types/node': ^25.6.0
  '@types/uniqid': ^5.3.4
  '@vitejs/plugin-vue': ^6.0.6
  '@vue/language-core': ^3.2.7
  '@vueuse/core': ^14.2.1
  element-plus: ^2.13.7
  eslint: ^10.2.1
  highlight.js: ^11.11.1
  husky: ^9.1.7
  lint-staged: ^16.4.0
  markdown-it: ^14.1.1
  markdown-it-anchor: ^9.2.0
  markdown-it-class: ^1.0.0
  markdown-it-container: ^4.0.0
  markdown-it-emoji: ^3.0.0
  markdown-it-toc-done-right: ^4.2.0
  rimraf: ^6.1.3
  sass: ^1.99.0
  stylelint: ^17.9.0
  stylelint-config-recommended: ^18.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^40.0.0
  stylelint-config-standard-scss: ^17.0.0
  tsdown: ^0.21.10
  typescript: ^6.0.3
  uniqid: ^5.4.0
  unplugin-auto-import: ^21.0.0
  unplugin-icons: ^23.0.1
  unplugin-vue-components: ^32.0.0
  vite: ^8.0.10
  vite-plugin-inspect: ^11.3.3
  vitest: ^4.1.5
  vue: ^3.6.0-beta.10
  vue-router: ^5.0.6
  vue-tsc: ^3.2.7
