/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiTyping: typeof import('./../src/components/components/globals/api-typing.vue')['default']
    CodeBox: typeof import('./../src/components/components/globals/code-box.vue')['default']
    DocPage: typeof import('./../src/components/components/globals/doc-page.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconCaretTop: typeof import('@element-plus/icons-vue')['CaretTop']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    VersionTag: typeof import('./../src/components/components/globals/version-tag.vue')['default']
  }
}
